<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;

/**
 * Seeder Guru & Tendik — data asli SMK Plus Al-Hilal (Oktober 2026).
 * Password default: password123 | updateOrCreate berdasarkan username.
 */
class GuruTendikSeeder extends Seeder
{
    public function run(): void
    {
        // ── Superadmin ────────────────────────────────────────────────────────
        User::updateOrCreate(
            ['username' => 'superadmin'],
            [
                'name'           => 'Super Administrator',
                'email'          => 'superadmin@hilaledu.sch.id',
                'password'       => 'password',
                'password_plain' => 'password',
                'role'           => 'superadmin',
                'is_active'      => true,
            ]
        );

        // ── Guru ─────────────────────────────────────────────────────────────
        $gurus = [
            [
                'name'           => 'Sokid, ST, M.Kom',
                'username'       => 'sokidbae',
                'email'          => 'sokidjunior5@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'akademik',
                'nip'            => '0000000000000099',
                'jabatan_utama'  => 'Wakasek Kurikulum & Akademik',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '082216715951',
                'alamat'         => 'BTN Ujungsemi Blok H1 No. 5',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Elin Tamaya, SE',
                'username'       => 'elintamaya',
                'email'          => 'elintamaya16@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'prakerin,keuangan,payroll',
                'nip'            => '8248772673230180',
                'jabatan_utama'  => 'Bendahara Sekolah / BOS',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '081234567890',
                'alamat'         => 'By Pass Tegalgubug',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Ismail Fahmi, ST',
                'username'       => 'ismailfahmi',
                'email'          => 'smkplusalhilalawn@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '3552773674130290',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '82217696063',
                'alamat'         => 'Blok 3 Al-Murtadho',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Muhammad Mansyur, S.Pt',
                'username'       => 'muhammadmansyur',
                'email'          => 'mm728419@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '6942767668130350',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '83807788828',
                'alamat'         => 'Blok Irigasi',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'M. NAJJINI, S.Pd',
                'username'       => 'mnajjini',
                'email'          => 'periwira@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'prakerin,tracer',
                'nip'            => '4156767668130340',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '8121411210',
                'alamat'         => 'Blok 02 Baitul Hikmah',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Moh. Roghib, S.Kom',
                'username'       => 'mohroghib',
                'email'          => 'roghib001@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'akademik',
                'nip'            => '9438779680130020',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '89612126802',
                'alamat'         => 'Al Ghozali',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Ani Mawaddatul Mukhlishoh, S.Pd',
                'username'       => 'animawaddatulmukhlishoh',
                'email'          => 'nie8kawaii@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '7240770671230190',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '85210002750',
                'alamat'         => 'Blok. Baitul Hikmah',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Dewi Priyatin, S.Pd',
                'username'       => 'dewipriyatin',
                'email'          => 'wiedewwie@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '7260770671130040',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '89654412828',
                'alamat'         => 'Blok Pontas',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Khayatun Nufus, S.Pd',
                'username'       => 'khayatunnufus',
                'email'          => 'nufuskhayatun617@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '1534774675230130',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '81283711076',
                'alamat'         => 'Taman Puri Sipulo',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'NUR AFIFAH, S.Pd',
                'username'       => 'nurafifah_1',
                'email'          => 'Af_ifah@yahoo.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '9247772673230300',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '895346000000',
                'alamat'         => 'Blok 05 Jl. Suropati',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'ALI MUSTOPA, S.Pd',
                'username'       => 'alimustopa',
                'email'          => 'mumucendana30@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '1543779680130060',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '895618000000',
                'alamat'         => 'Sumur Dadap',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Rizki Dwi Safitri, S.Pd',
                'username'       => 'rizkidwisafitri',
                'email'          => 'rizkidwisafitri38@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'koperasi',
                'nip'            => '9261772673230210',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '895336000000',
                'alamat'         => 'Blok Karanganyar',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Dra. Roisah',
                'username'       => 'draroisah',
                'email'          => 'roisahiis68@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '9960746648300060',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '85314333771',
                'alamat'         => 'Dusun Manis',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Saefullah, S.Pd.I',
                'username'       => 'saefullah',
                'email'          => 'sifaasep5359@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'prakerin',
                'nip'            => '4353761662130100',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '89619420287',
                'alamat'         => 'Blok 5 Tegalhubug Lor',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'SITI KOMALA SARI, S.Pd',
                'username'       => 'sitikomalasari',
                'email'          => 'mala.ms188@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '5940773674230320',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '8999629664',
                'alamat'         => 'Blok 03 Al-Qudsiyah Wetan',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Yuliyanti, S.Pd.I',
                'username'       => 'yuliyanti_1',
                'email'          => 'yuliyantifaqi@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '3837769670230400',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '82115903008',
                'alamat'         => 'Tegalgubug',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Yunani Elok, S.Pd',
                'username'       => 'yunanielok',
                'email'          => 'yunanielok@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'bk,keuangan,tracer',
                'nip'            => '1543779680230040',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '83178553202',
                'alamat'         => 'Blok Cemeti',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Aty Riswanty',
                'username'       => 'atyriswanty',
                'email'          => '543771672230332@guru.hilaledu.sch.id',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '543771672230332',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '83824617277',
                'alamat'         => 'Blok III',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Abdul Fatah, ST',
                'username'       => 'abdulfatah',
                'email'          => 'fatah.cfc@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'akademik,bk,tracer',
                'nip'            => '7860774675130280',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '89675267008',
                'alamat'         => 'Blok 4 Dar Al Quran',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Silvi Dwi Manitik S.pd',
                'username'       => 'silvidwimanitik',
                'email'          => 'silvicrb736@gmail.com',
                'role'           => 'guru',
                'admin_role'     => 'koperasi',
                'nip'            => '0000000000000001',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '83845906618',
                'alamat'         => 'Blok 2 RT 002/003',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Jefri Handa, A.Md',
                'username'       => 'jefrihanda',
                'email'          => 'jefrihanda77@Gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000019',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '81322796343',
                'alamat'         => 'Tegalgubug',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'MALIKHA, S.Pd',
                'username'       => 'malikha',
                'email'          => '0000000000000002@guru.hilaledu.sch.id',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000002',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '89664017587',
                'alamat'         => 'Blok 3 Pojok Siar',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'NIDZOMUDDIN, Amd',
                'username'       => 'nidzomuddin',
                'email'          => 'Nidzomuddinesemka@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000003',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '89639832672',
                'alamat'         => 'Jl. Raya Suropati Blok Al-Muqoyim',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'M.Kholid S.Ag',
                'username'       => 'kholid',
                'email'          => 'kholid@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000004',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '81321361629',
                'alamat'         => 'Blo. 3 Wali Sanga',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Siti Saro, S.Pd',
                'username'       => 'sitisaro',
                'email'          => 'sitisaro2204@upi.edu',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000005',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '83113035228',
                'alamat'         => 'Prajawinangun Wetan',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Fitriyanti S.Pd',
                'username'       => 'fitriyanti',
                'email'          => 'ghofarghofar801@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000006',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '83147238051',
                'alamat'         => 'Blok 05 BTN Taman Puri Sipul',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'VIAUNILLAHI TASYA',
                'username'       => 'viaunillahitasya',
                'email'          => 'fiaunillahitasya15@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000007',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'P',
                'no_hp'          => '8211170829',
                'alamat'         => 'Blok 4 Al Anwariyyah',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'M Sabiqul Huda',
                'username'       => 'MSabiqulHuda',
                'email'          => 'sabiq@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000013',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '082216715951',
                'alamat'         => 'BTN SIPULO',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Melinda, SE',
                'username'       => 'melinda',
                'email'          => 'melindaizdihaar@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000014',
                'jabatan_utama'  => 'Guru',
                'jenis_kelamin'  => null,
                'no_hp'          => null,
                'alamat'         => null,
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'KH. Nadziri Syirodz',
                'username'       => 'nasrudin',
                'email'          => 'nasrudin@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '',
                'jabatan_utama'  => 'Guru Pesantren',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '081234567890',
                'alamat'         => 'Pondok Pesantren Al-Hilal',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Syagif',
                'username'       => 'Syagif',
                'email'          => 'syagif@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => null,
                'jabatan_utama'  => 'Guru Pesantren',
                'jenis_kelamin'  => 'L',
                'no_hp'          => '081234567891',
                'alamat'         => 'Pondok Pesantren Al-Hilal',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Uts. Masrudin',
                'username'       => 'masrudin',
                'email'          => 'masrudin@gmail.com',
                'role'           => 'guru',
                'admin_role'     => null,
                'nip'            => '0000000000000078',
                'jabatan_utama'  => 'Guru Pengajar',
                'jenis_kelamin'  => 'L',
                'no_hp'          => null,
                'alamat'         => null,
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
        ];

        foreach ($gurus as $g) {
            User::updateOrCreate(['username' => $g['username']], $g);
        }

        $this->command->info('Guru seeded (' . count($gurus) . ' records).');

        // ── Tendik ────────────────────────────────────────────────────────────
        $tendiks = [
            [
                'name'           => 'Siti Nurhaliza',
                'username'       => 'tendik01',
                'email'          => 'tendik01@hilaledu.sch.id',
                'role'           => 'tendik',
                'nip'            => '2345678901234567',
                'jabatan_utama'  => 'Tendik',
                'jenis_kelamin'  => 'P',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Syarif Hidayatullah, S.Pd',
                'username'       => 'syarif01',
                'email'          => 'syarief26@gmail.com',
                'role'           => 'tendik',
                'nip'            => null,
                'jabatan_utama'  => 'Tendik',
                'jenis_kelamin'  => 'L',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Khaerul Wafiq, S.Sos',
                'username'       => 'admintu2',
                'email'          => 'khaerulerul@gmail.com',
                'role'           => 'tendik',
                'nip'            => null,
                'jabatan_utama'  => 'Tendik',
                'jenis_kelamin'  => 'L',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
            [
                'name'           => 'Muhammad Habibullah',
                'username'       => 'admintu3',
                'email'          => 'mhabibullah650@gmail.com',
                'role'           => 'tendik',
                'nip'            => null,
                'jabatan_utama'  => 'Tendik',
                'jenis_kelamin'  => 'L',
                'is_active'      => true,
                'password'       => 'password123',
                'password_plain' => 'password123',
            ],
        ];

        foreach ($tendiks as $t) {
            User::updateOrCreate(['username' => $t['username']], $t);
        }

        $this->command->info('Tendik seeded (' . count($tendiks) . ' records).');
    }
}
