<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/**
 * Seeder Siswa — data asli SMK Plus Al-Hilal (Oktober 2026).
 * 220 siswa, 9 kelas (X-XII), TA 2026/2027.
 * kelas_id diambil dinamis dari nama kelas agar aman setelah re-seed.
 * Password default: siswa123
 */
class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        $kelas = fn(string $nama) => DB::table('kelas')->where('nama', $nama)->value('id');

        $data = [
            // ── X AKL (22 siswa) ────────────────────────────────────────────
            ['Agung Maulana Putra',    'agungmaulanaputra',    'AgungMaulanaPutra@hilaledu.sch.id',    '262721001', 'X AKL', 'L'],
            ['Dennis Alfian',          'dennisalfian',         'DennisAlfian@hilaledu.sch.id',         '262721002', 'X AKL', 'L'],
            ['Dwi Novi Yani',          'dwinoviyani',          'DwiNoviYani@hilaledu.sch.id',          '262721003', 'X AKL', 'P'],
            ['Inda Lasmawati',         'indalasmawati',        'IndaLasmawati@hilaledu.sch.id',        '262721004', 'X AKL', 'P'],
            ['Istianah',               'istianah',             'Istianah@hilaledu.sch.id',             '262721005', 'X AKL', 'P'],
            ['Isyti Ishamatal Aula',   'isytiishamatalaula',   'IsytiIshamatalAula@hilaledu.sch.id',   '262721006', 'X AKL', 'P'],
            ['Jihan',                  'jihan',                'Jihan@hilaledu.sch.id',                '262721007', 'X AKL', 'P'],
            ['Kanna Sabilah',          'kannasabilah',         'KannaSabilah@hilaledu.sch.id',         '262721008', 'X AKL', 'P'],
            ['Muhammad Ghifari Adha',  'muhammadghifariadha',  'MuhammadGhifariAdha@hilaledu.sch.id',  '262721009', 'X AKL', 'L'],
            ['Muhammad Rafa Ramadhan', 'muhammadrafaramadhan', 'MuhammadRafaRamadhan@hilaledu.sch.id', '262721010', 'X AKL', 'L'],
            ['Mukhamad Alvin Najmi',   'mukhamadalvinnajmi',   'MukhamadAlvinNajmi@hilaledu.sch.id',   '262721011', 'X AKL', 'L'],
            ['Mutiara Novita',         'mutiaranovita',        'MutiaraNovita@hilaledu.sch.id',        '262721012', 'X AKL', 'P'],
            ['Najma Auralia',          'najmaauralia',         'NajmaAuralia@hilaledu.sch.id',         '262721013', 'X AKL', 'P'],
            ['Nining Ampeli',          'niningampeli',         'NiningAmpeli@hilaledu.sch.id',         '262721014', 'X AKL', 'P'],
            ['Nizar',                  'nizar',                'Nizar@hilaledu.sch.id',                '262721015', 'X AKL', 'L'],
            ['Nizatul Aula',           'nizatulaula',          'NizatulAula@hilaledu.sch.id',          '262721016', 'X AKL', 'P'],
            ['Novita Sari',            'novitasari',           'NovitaSari@hilaledu.sch.id',           '262721017', 'X AKL', 'P'],
            ['Nur Larasati',           'nurlarasati',          'NurLarasati@hilaledu.sch.id',          '262721018', 'X AKL', 'P'],
            ['Rizka Maulidiyah',       'rizkamaulidiyah',      'RizkaMaulidiyah@hilaledu.sch.id',      '262721019', 'X AKL', 'P'],
            ['Rodhotul Nurul Khasanah','rodhotulnurulkhasanah','RodhotulNurulKhasanah@hilaledu.sch.id','262721020', 'X AKL', 'P'],
            ["Ro'ihatul Jannah",       'roihatuljannah',       "Ro'ihatulJannah@hilaledu.sch.id",      '262721021', 'X AKL', 'P'],
            ['Sela Rizqi Oliyah',      'selarizqioliyah',      'SelaRizqiOliyah@hilaledu.sch.id',      '262721022', 'X AKL', 'P'],
            // ── XI AKL (29 siswa) ───────────────────────────────────────────
            ['A. Fahim Kholil',            'a.fahimkholil',            'A.FahimKholil@hilaledu.sch.id',            '252621001', 'XI AKL', 'L'],
            ['Anis Sobiyah',               'anissobiyah',              'AnisSobiyah@hilaledu.sch.id',              '252621002', 'XI AKL', 'P'],
            ['Deni Saputra',               'denisaputra',              'DeniSaputra@hilaledu.sch.id',              '252621003', 'XI AKL', 'L'],
            ['Diana Tari Aprilliyani',     'dianatariaprilliyani',     'DianaTariAprilliyani@hilaledu.sch.id',     '252621004', 'XI AKL', 'L'],
            ['Dini Putri Aulia',           'diniputriaulia',           'DiniPutriAulia@hilaledu.sch.id',           '252621005', 'XI AKL', 'P'],
            ['Diva Khofifah',              'divakhofifah',             'DivaKhofifah@hilaledu.sch.id',             '252621006', 'XI AKL', 'P'],
            ['Dwi Aulia Novianti',         'dwiaulianovianti',         'DwiAuliaNovianti@hilaledu.sch.id',         '252621007', 'XI AKL', 'P'],
            ['Fadil Aqli',                 'fadilaqli',                'FadilAqli@hilaledu.sch.id',                '252621008', 'XI AKL', 'L'],
            ['Fazriyah',                   'fazriyah',                 'Fazriyah@hilaledu.sch.id',                 '252621009', 'XI AKL', 'P'],
            ['Giska Falentina',            'giskafalentina',           'GiskaFalentina@hilaledu.sch.id',           '252621010', 'XI AKL', 'P'],
            ['Khaidar Ali',                'khaidarali',               'KhaidarAli@hilaledu.sch.id',               '252621011', 'XI AKL', 'L'],
            ['Khilyatunnisa',              'khilyatunnisa',            'Khilyatunnisa@hilaledu.sch.id',            '252621012', 'XI AKL', 'P'],
            ['M. Revan Afiriliansah',      'm.revanafiriliansah',      'M.RevanAfiriliansah@hilaledu.sch.id',      '252621013', 'XI AKL', 'L'],
            ['Meilani Nafisah Ramadhanti', 'meilaninafisahramadhanti', 'MeilaniNafisahRamadhanti@hilaledu.sch.id', '252621014', 'XI AKL', 'L'],
            ['Moh. Bilal',                 'moh.bilal',                'Moh.Bilal@hilaledu.sch.id',                '252621015', 'XI AKL', 'L'],
            ['Muhamad Al Barqowie',        'muhamadalbarqowie',        'MuhamadAlBarqowie@hilaledu.sch.id',        '252621016', 'XI AKL', 'L'],
            ['Muhamad Tafa Assyifa',       'muhamadtafaassyifa',       'MuhamadTafaAssyifa@hilaledu.sch.id',       '252621017', 'XI AKL', 'L'],
            ['Muhammad Abdul Aziz',        'muhammadabdulaziz',        'MuhammadAbdulAziz@hilaledu.sch.id',        '252621018', 'XI AKL', 'L'],
            ['NISA ZAKIYAH',               'nisazakiyah',              'NISAKAKIYAH@hilaledu.sch.id',              '242521019', 'XI AKL', 'P'],
            ['Nurul Fatikha',              'nurulfatikha',             'NurulFatikha@hilaledu.sch.id',             '252621020', 'XI AKL', 'L'],
            ['Qolbiyatun Nadhifah',        'qolbiyatunnadhifah',       'QolbiyatunNadhifah@hilaledu.sch.id',       '252621021', 'XI AKL', 'P'],
            ['Sainah',                     'sainah',                   'Sainah@hilaledu.sch.id',                   '252621022', 'XI AKL', 'P'],
            ['Shiren Ramadani',            'shirenramadani',           'ShirenRamadani@hilaledu.sch.id',           '252621023', 'XI AKL', 'P'],
            ['Shofa Rahayu',               'shofarahayu',              'ShofaRahayu@hilaledu.sch.id',              '252621024', 'XI AKL', 'P'],
            ['Sintia Bella',               'sintiabella',              'SintiaBella@hilaledu.sch.id',              '252621025', 'XI AKL', 'P'],
            ['Sri Rahayu Lestari',         'srirahayulestari',         'SriRahayuLestari@hilaledu.sch.id',         '252621027', 'XI AKL', 'P'],
            ['Tisya Nafila',               'tisyanafila',              'TisyaNafila@hilaledu.sch.id',              '252621028', 'XI AKL', 'P'],
            ['Yusuf Ibrahim',              'yusufibrahim',             'YusufIbrahim@hilaledu.sch.id',             '252621029', 'XI AKL', 'L'],
            ['Muhammad Farid Nabil',       'muhammadfaridnabil',       'MuhammadFaridNabil@hilaledu.sch.id',       '252621030', 'XI AKL', 'L'],
            // ── XII AKL (20 siswa) ──────────────────────────────────────────
            ['ABDUL KHAMID YANAL',     'abdulkhamidyanal',     'ABDULKHAMIDYANAL@hilaledu.sch.id',     '242521001', 'XII AKL', 'L'],
            ['AYU TIAH RAKHMAH',       'ayutiahrakhmah',       'AYUTIAHRAKHMAH@hilaledu.sch.id',       '242521004', 'XII AKL', 'P'],
            ['BELVA MAULIDA AWALIYAH', 'belvamaulidaawaliyah', 'BELVAMAULIDAAWALIYAH@hilaledu.sch.id', '242521005', 'XII AKL', 'P'],
            ['DAWAI MILLATINNAFIAH',   'dawaimillatinnafiah',  'DAWAIMILLATINNAFIAH@hilaledu.sch.id',  '242521006', 'XII AKL', 'P'],
            ['DUROTUNNAQIYAH',         'durotunnaqiyah',       'DUROTUNNAQIYAH@hilaledu.sch.id',       '242521007', 'XII AKL', 'P'],
            ['HANIF RINGGING PRATAMA', 'hanifringgingpratama', 'HANIFRINGGINGPRATAMA@hilaledu.sch.id', '242521010', 'XII AKL', 'L'],
            ['IVETH JEANNE JUNIELLE',  'ivethjeannejunielle',  'IVETHJEANNEJUNIELLE@hilaledu.sch.id',  '242521012', 'XII AKL', 'P'],
            ['KHILYATUS SAADAH',       'khilyatussaadah',      'KHILYATUSSAADAH@hilaledu.sch.id',      '242521013', 'XII AKL', 'P'],
            ['KHOERUNNISA',            'khoerunnisa',          'KHOERUNNISA@hilaledu.sch.id',          '242521014', 'XII AKL', 'P'],
            ['MAR ATUS SHOLIKHA',      'maratussholikha',      'MARATUSSHOLIKHA@hilaledu.sch.id',      '242521015', 'XII AKL', 'P'],
            ['MARUSANAH',              'marusanah',            'MARUSANAH@hilaledu.sch.id',            '242521016', 'XII AKL', 'P'],
            ['MOH SABIKH BAKHRUL ALAM','mohsabikhbakhrulalam', 'MOHSABIKHBAKHRULALAM@hilaledu.sch.id', '242521017', 'XII AKL', 'L'],
            ['NABILA SYIFA JULIANA',   'nabilasyifajuliana',   'NABILASYIFAJULIANA@hilaledu.sch.id',   '242521018', 'XII AKL', 'P'],
            ['PUTRI FIRANA ARYANI',    'putrifiranaaryani',    'PUTRIFIRANAARYANI@hilaledu.sch.id',    '242521020', 'XII AKL', 'P'],
            ['PUTRI KHAERUNISA',       'putrikhaerunisa',      'PUTRIKHAERUNISA@hilaledu.sch.id',      '242521021', 'XII AKL', 'P'],
            ['RIYANTI',                'riyanti',              'RIYANTI@hilaledu.sch.id',              '242521022', 'XII AKL', 'P'],
            ['SINTA RAMADANI',         'sintaramadani',        'SINTARAMADANI@hilaledu.sch.id',        '242521023', 'XII AKL', 'P'],
            ['SRI DAMAYANTI',          'sridamayanti',         'SRIDAMAYANTI@hilaledu.sch.id',         '242521024', 'XII AKL', 'P'],
            ['ZIYAD RIZQI',            'ziyadrizqi',           'ZIYADRIZQI@hilaledu.sch.id',           '242521025', 'XII AKL', 'L'],
            ['NYIMAS PAKUNGWATI',      'nyimaspakungwati',     'NYIMASPAKUNGWATI@hilaledu.sch.id',     '242521026', 'XII AKL', 'P'],
            // ── X TKJT (23 siswa) ───────────────────────────────────────────
            ['Abdullah Al Gifari',         'abdullahalgifari',        'AbdullahAlGifari@hilaledu.sch.id',        '262711001', 'X TKJT', 'L'],
            ['Alfiyatun Najwa',            'alfiyatunnajwa',          'AlfiyatunNajwa@hilaledu.sch.id',          '262711002', 'X TKJT', 'P'],
            ['Ali Maluf Rizki Me',         'alimalufrizkime',         'AliMalufRizkiMe@hilaledu.sch.id',         '262711003', 'X TKJT', 'L'],
            ['Anida Rifqo',                'anidarifqo',              'AnidaRifqo@hilaledu.sch.id',              '262711004', 'X TKJT', 'P'],
            ['Arini',                      'arini',                   'Arini@hilaledu.sch.id',                   '262711005', 'X TKJT', 'P'],
            ['Bagas Al Ghozali',           'bagasalghozali',          'BagasAlGhozali@hilaledu.sch.id',          '262711006', 'X TKJT', 'L'],
            ['Diana Putri Solekha',        'dianaputrisolekha',       'DianaPutriSolekha@hilaledu.sch.id',       '262711007', 'X TKJT', 'P'],
            ['Dicky Fahrozy',              'dickyfahrozy',            'DickyFahrozy@hilaledu.sch.id',            '262711008', 'X TKJT', 'L'],
            ['Fahri Aditya Rahman',        'fahriadityarahman',       'FahriAdityaRahman@hilaledu.sch.id',       '262711009', 'X TKJT', 'L'],
            ['Fitri Nurhasanah',           'fitrinurhasanah',         'FitriNurhasanah@hilaledu.sch.id',         '262711010', 'X TKJT', 'P'],
            ['Fitriya Azzahra',            'fitriyaazzahra',          'FitriyaAzzahra@hilaledu.sch.id',          '262711011', 'X TKJT', 'P'],
            ['Khafidotunnisa Octovia',     'khafidotunnisaoctovia',   'KhafidotunnisaOctovia@hilaledu.sch.id',   '262711012', 'X TKJT', 'P'],
            ['Lulu Ulatfiatul Jannah',     'luluulatfiatuljannah',    'LuluUlatfiatulJannah@hilaledu.sch.id',    '262711013', 'X TKJT', 'P'],
            ['M Bayu Arkhan',              'mbayuarkhan',             'MBayuArkhan@hilaledu.sch.id',             '262711014', 'X TKJT', 'L'],
            ['Moh. Rizki Firdaus',         'moh.rizkifirdaus',        'Moh.RizkiFirdaus@hilaledu.sch.id',        '262711015', 'X TKJT', 'L'],
            ['Mohamad Fahril Khuzzaeni FS','mohamadfahrilkhuzzaenifs', 'MohamadFahrilKhuzzaeniFS@hilaledu.sch.id','262711016','X TKJT', 'L'],
            ['Mokhamad Rifki',             'mokhamadrifki',           'MokhamadRifki@hilaledu.sch.id',           '262711017', 'X TKJT', 'L'],
            ['Muhammad Amri Assodik',      'muhammadamriassodik',     'MuhammadAmriAssodik@hilaledu.sch.id',     '262711018', 'X TKJT', 'L'],
            ['Muhammad Fadil Dafik',       'muhammadfadildafik',      'MuhammadFadilDafik@hilaledu.sch.id',      '262711019', 'X TKJT', 'L'],
            ['Reza Ahmad Zidan',           'rezaahmadzidan',          'RezaAhmadZidan@hilaledu.sch.id',          '262711020', 'X TKJT', 'L'],
            ['Rifki Haikal',               'rifkihaikal',             'RifkiHaikal@hilaledu.sch.id',             '262711021', 'X TKJT', 'L'],
            ['Tirta Wiguna',               'tirtawiguna',             'TirtaWiguna@hilaledu.sch.id',             '262711022', 'X TKJT', 'L'],
            ['Fiqi Febrian',               'fiqifebrian',             'FiqiFebrian@hilaledu.sch.id',             '262711023', 'X TKJT', 'L'],
            // ── XI TKJT (39 siswa) ──────────────────────────────────────────
            ['Adrian Nur Iman',                'adriannuriman',            'AdrianNurIman@hilaledu.sch.id',            '252611002', 'XI TKJT', 'L'],
            ['Anim Falahudin',                 'animfalahudin',            'AnimFalahudin@hilaledu.sch.id',            '252611003', 'XI TKJT', 'L'],
            ['Ashabul Kahfi',                  'ashabulkahfi',             'AshabulKahfi@hilaledu.sch.id',             '252611004', 'XI TKJT', 'L'],
            ['Aslam Nafis',                    'aslamnafis',               'AslamNafis@hilaledu.sch.id',               '252611005', 'XI TKJT', 'L'],
            ['Azka Rifai',                     'azkarifai',                'AzkaRifai@hilaledu.sch.id',                '252611006', 'XI TKJT', 'L'],
            ['Fanessya Azzahratu Xeina',       'fanessyaazzahratuxeina',   'FanessyaAzzahratuXeina@hilaledu.sch.id',   '252611007', 'XI TKJT', 'P'],
            ['Fatimatuzzahratu Ramdhanil W',   'fatimatuzzahraturamdhanilw','FatimatuzzahratuRamdhanilW@hilaledu.sch.id','252611008','XI TKJT','P'],
            ['Firda Auliyah',                  'firdaauliyah',             'FirdaAuliyah@hilaledu.sch.id',             '252611009', 'XI TKJT', 'P'],
            ['Fitriyani',                      'fitriyani',                'Fitriyani@hilaledu.sch.id',                '252611010', 'XI TKJT', 'P'],
            ['Habibah Nurrosiana Dewi',        'habibahnurrosianadewi',    'HabibahNurrosianaDewi@hilaledu.sch.id',    '252611011', 'XI TKJT', 'P'],
            ['Haikal Kasavani',                'haikalkasavani',           'HaikalKasavani@hilaledu.sch.id',           '252611012', 'XI TKJT', 'L'],
            ['Ilan Ilahi',                     'ilanilahi',                'IlanIlahi@hilaledu.sch.id',                '252611013', 'XI TKJT', 'L'],
            ['Khoiriyah Muntazah',             'khoiriyahmuntazah',        'KhoiriyahMuntazah@hilaledu.sch.id',        '252611014', 'XI TKJT', 'P'],
            ['Liyana Zahirah',                 'liyanazahirah',            'LiyanaZahirah@hilaledu.sch.id',            '252611015', 'XI TKJT', 'P'],
            ['Maulidah Khasana',               'maulidahkhasana',          'MaulidahKhasana@hilaledu.sch.id',          '252611016', 'XI TKJT', 'P'],
            ['Moh. Akhfad Khaizin',            'moh.akhfadkhaizin',        'Moh.AkhfadKhaizin@hilaledu.sch.id',        '252611018', 'XI TKJT', 'L'],
            ['Moh. Haidar Rizqi',              'moh.haidarrizqi',          'Moh.HaidarRizqi@hilaledu.sch.id',          '252611019', 'XI TKJT', 'L'],
            ['Mohammad Azwan Fahad',           'mohammadazwanfahad',       'MohammadAzwanFahad@hilaledu.sch.id',       '252611020', 'XI TKJT', 'L'],
            ['Mohammad Warosy Furaedy',        'mohammadwarosyfuraedy',    'MohammadWarosyFuraedy@hilaledu.sch.id',    '252611021', 'XI TKJT', 'L'],
            ['Muhammad Arif Maulana',          'muhammadarifmaulana',      'MuhammadArifMaulana@hilaledu.sch.id',      '252611022', 'XI TKJT', 'L'],
            ['Muhamad Fathan Bilal Pratama',   'muhamadfathanbilalpratama', 'MuhamadFathanBilalPratama@hilaledu.sch.id','252611023','XI TKJT','L'],
            ['Muhamad Rizqi Ramadhan',         'muhamadrizqiramadhan',     'MuhamadRizqiRamadhan@hilaledu.sch.id',     '252611024', 'XI TKJT', 'L'],
            ['Muhammad Azri Abdillah',         'muhammadazriabdillah',     'MuhammadAzriAbdillah@hilaledu.sch.id',     '252611025', 'XI TKJT', 'L'],
            ['Muhammad Faahim Haasyimiyya',    'muhammadfaahimhaasyimiyya', 'MuhammadFaahimHaasyimiyya@hilaledu.sch.id','252611026','XI TKJT','L'],
            ['Muhammad Hilmi',                 'muhammadhilmi',            'MuhammadHilmi@hilaledu.sch.id',            '252611028', 'XI TKJT', 'L'],
            ['Muhammad Ilham Lubis',           'muhammadilhamlubis',       'MuhammadIlhamLubis@hilaledu.sch.id',       '252611029', 'XI TKJT', 'L'],
            ['Muhammad Ilham Ramdani',         'muhammadilhamramdani',     'MuhammadIlhamRamdani@hilaledu.sch.id',     '252611030', 'XI TKJT', 'L'],
            ['Muhammad Nurribkhi',             'muhammadnurribkhi',        'MuhammadNurribkhi@hilaledu.sch.id',        '252611031', 'XI TKJT', 'L'],
            ['Nazwa Ameliah',                  'nazwaameliah',             'NazwaAmeliah@hilaledu.sch.id',             '252611032', 'XI TKJT', 'P'],
            ['Niken Seliya Rahmawati',         'nikenseliyarahmawati',     'NikenSeliyaRahmawati@hilaledu.sch.id',     '252611033', 'XI TKJT', 'P'],
            ['Novita Isnaeni',                 'novitaisnaeni',            'NovitaIsnaeni@hilaledu.sch.id',            '252611034', 'XI TKJT', 'P'],
            ['Nur Afifah',                     'nurafifah',                'NurAfifah@hilaledu.sch.id',                '252611035', 'XI TKJT', 'P'],
            ['Nur Yuliana',                    'nuryuliana',               'NurYuliana@hilaledu.sch.id',               '252611036', 'XI TKJT', 'P'],
            ['Putri Amaliah',                  'putriamaliah',             'PutriAmaliah@hilaledu.sch.id',             '252611037', 'XI TKJT', 'P'],
            ['Salsabila Ramadhani',            'salsabilaramadhani',       'SalsabilaRamadhani@hilaledu.sch.id',       '252611038', 'XI TKJT', 'L'],
            ['Siti Maghfuroh',                 'sitimaghfuroh',            'SitiMaghfuroh@hilaledu.sch.id',            '252611039', 'XI TKJT', 'P'],
            ['Tania Maulidia Putri',           'taniamaulidiaputri',       'TaniaMaulidiaPutri@hilaledu.sch.id',       '252611040', 'XI TKJT', 'P'],
            ['Siti Nurfaizah',                 'sitinurfaizah',            'SitiNurfaizah@hilaledu.sch.id',            '252611041', 'XI TKJT', 'P'],
            // ── XII TKJT (19 siswa) ─────────────────────────────────────────
            ['AKMAL MUSYAFFA',          'akmalmusyaffa',          'AKMALMUSYAFFA@hilaledu.sch.id',          '242511001', 'XII TKJT', 'L'],
            ['APRILIYANTI',             'apriliyanti',            'APRILIYANTI@hilaledu.sch.id',            '242511002', 'XII TKJT', 'P'],
            ['BELVI MAULIDA AWALIYANAH','belvimaulidaawaliyanah', 'BELVIMAULIDAAWALIYANAH@hilaledu.sch.id', '242511003', 'XII TKJT', 'P'],
            ['DIMAH SALSABILAH',        'dimahsalsabilah',        'DIMAHSALSABILAH@hilaledu.sch.id',        '242511005', 'XII TKJT', 'P'],
            ['IBDA ZELFI MUBAROK',      'ibdazelfimubarok',       'IBDAZELFIMUBAROK@hilaledu.sch.id',       '242511007', 'XII TKJT', 'L'],
            ['INNE ADINDA MITHA',       'inneadindamitha',        'INNEADINDAMITHA@hilaledu.sch.id',        '242511008', 'XII TKJT', 'P'],
            ['JIHAN FAIRAH',            'jihanfairah',            'JIHANFAIRAH@hilaledu.sch.id',            '242511009', 'XII TKJT', 'P'],
            ['KHILDATUL JANNAH',        'khildatuljannah',        'KHILDATULJANNAH@hilaledu.sch.id',        '242511010', 'XII TKJT', 'P'],
            ['MOH HERU',                'mohheru',                'MOHHERU@hilaledu.sch.id',                '242511012', 'XII TKJT', 'L'],
            ['MOHAMMAD ABDUL AZIS',     'mohammadabdulazis',      'MOHAMMADABDULAZIS@hilaledu.sch.id',      '242511013', 'XII TKJT', 'L'],
            ['MUHAMAD FAHREVI',         'muhamadfahrevi',         'MUHAMADFAHREVI@hilaledu.sch.id',         '242511015', 'XII TKJT', 'L'],
            ['MUHAMAD SAEPUL BAHRI',    'muhamadsaepulbahri',     'MUHAMADSAEPULBAHRI@hilaledu.sch.id',     '242511016', 'XII TKJT', 'L'],
            ['RIFANI',                  'rifani',                 'RIFANI@hilaledu.sch.id',                 '242511017', 'XII TKJT', 'P'],
            ['RINA ASTNA FADILA',       'rinaastnafadila',        'RINAASTNAFADILA@hilaledu.sch.id',        '242511018', 'XII TKJT', 'P'],
            ['RIYAN HIDAYATULLOH',      'riyanhidayatulloh',      'RIYANHIDAYATULLOH@hilaledu.sch.id',      '242511019', 'XII TKJT', 'L'],
            ['SALMAH FADILAH',          'salmahfadilah',          'SALMAHFADILAH@hilaledu.sch.id',          '242511020', 'XII TKJT', 'P'],
            ['ULYA QONITAH',            'ulyaqonitah',            'ULYAQONITAH@hilaledu.sch.id',            '242511021', 'XII TKJT', 'P'],
            ['YULIYANTI',               'yuliyanti',              'YULIYANTI@hilaledu.sch.id',              '242511022', 'XII TKJT', 'P'],
            ['MOHAMMAD ASLIKH',         'mohammadaslikh',         'MOHAMMADASLIKH@hilaledu.sch.id',         '242511023', 'XII TKJT', 'L'],
            // ── X TO (25 siswa) ─────────────────────────────────────────────
            ['Abdullah Kafabihi',         'abdullahkafabihi',      'AbdullahKafabihi@hilaledu.sch.id',      '262731001', 'X TO', 'L'],
            ['Aditya Mohammad Septian',   'adityamohammadseptian', 'AdityaMohammadSeptian@hilaledu.sch.id', '262731002', 'X TO', 'L'],
            ['Alvin Akmal Malik',         'alvinakmalmalik',       'AlvinAkmalMalik@hilaledu.sch.id',       '262731003', 'X TO', 'L'],
            ['Asad Sofyan Hadi',          'asadsofyanhadi',        'AsadSofyanHadi@hilaledu.sch.id',        '262731004', 'X TO', 'L'],
            ['Bagus',                     'bagus',                 'Bagus@hilaledu.sch.id',                 '262731005', 'X TO', 'L'],
            ['Dimas Khasfian',            'dimaskhasfian',         'DimasKhasfian@hilaledu.sch.id',         '262731006', 'X TO', 'L'],
            ['Fahad Hukul',               'fahadhukul',            'FahadHukul@hilaledu.sch.id',            '262731007', 'X TO', 'L'],
            ['Farhad Rama Dinata',        'farhadramadinata',      'FarhadRamaDinata@hilaledu.sch.id',      '262731008', 'X TO', 'L'],
            ['Febri Febriyan Fadilah',    'febrifebriyanfadilah',  'FebriFebriyanFadilah@hilaledu.sch.id',  '262731009', 'X TO', 'L'],
            ['Hafizh Maulana',            'hafizhmaulana',         'HafizhMaulana@hilaledu.sch.id',         '262731010', 'X TO', 'L'],
            ['Lutfi',                     'lutfi',                 'Lutfi@hilaledu.sch.id',                 '262731011', 'X TO', 'L'],
            ['Mahesa Jenar',              'mahesajenar',           'MahesaJenar@hilaledu.sch.id',           '262731012', 'X TO', 'L'],
            ['Moh Ubaidillah',            'mohubaidillah',         'MohUbaidillah@hilaledu.sch.id',         '262731013', 'X TO', 'L'],
            ['Mohammad Ibrahim',          'mohammadibrahim',       'MohammadIbrahim@hilaledu.sch.id',       '262731014', 'X TO', 'L'],
            ['Muhamad Rifki',             'muhamadrifki',          'MuhamadRifki@hilaledu.sch.id',          '262731015', 'X TO', 'L'],
            ['Muhammad Hisyam Abrori',    'muhammadhisyamabrori',  'MuhammadHisyamAbrori@hilaledu.sch.id',  '262731016', 'X TO', 'L'],
            ['Muhammad Salman Al Farizi', 'muhammadsalmanalfarizi','MuhammadSalmanAlFarizi@hilaledu.sch.id', '262731017', 'X TO', 'L'],
            ['Muhammad Yasir Arafat',     'muhammadyasirarafat',   'MuhammadYasirArafat@hilaledu.sch.id',   '262731018', 'X TO', 'L'],
            ['Mukhamad Ibnu Fareza',      'mukhamadibnufareza',    'MukhamadIbnuFareza@hilaledu.sch.id',    '262731019', 'X TO', 'L'],
            ['Muzzakin',                  'muzzakin',              'Muzzakin@hilaledu.sch.id',              '262731020', 'X TO', 'L'],
            ['Nanda Saputra',             'nandasaputra',          'NandaSaputra@hilaledu.sch.id',          '262731021', 'X TO', 'L'],
            ['Rifqi Alka Maulana',        'rifqialkamaulana',      'RifqiAlkaMaulana@hilaledu.sch.id',      '262731023', 'X TO', 'L'],
            ['Tri Putra Rizky',           'triputrarizky',         'TriPutraRizky@hilaledu.sch.id',         '262731024', 'X TO', 'L'],
            ['Hasan Hariri Ibrohim',      'hasanhaririibrohim',    'HasanHaririIbrohim@hilaledu.sch.id',    '262731025', 'X TO', 'L'],
            ['Albi Fachriyan',            'albifachriyan',         'AlbiFachriyan@hilaledu.sch.id',         '262731026', 'X TO', 'L'],
            // ── XI TO (27 siswa) ────────────────────────────────────────────
            ['Abdul Kholid',             'abdulkholid',           'AbdulKholid@hilaledu.sch.id',           '252631001', 'XI TO', 'L'],
            ['Ahmad Abdul Mughits',      'ahmadabdulmughits',     'AhmadAbdulMughits@hilaledu.sch.id',     '252631003', 'XI TO', 'L'],
            ['Dede Saputra',             'dedesaputra',           'DedeSaputra@hilaledu.sch.id',           '252631008', 'XI TO', 'L'],
            ['Deni Aliansyah',           'denialiansyah',         'DeniAliansyah@hilaledu.sch.id',         '252631009', 'XI TO', 'L'],
            ['Dude Herlino',             'dudeherlino',           'DudeHerlino@hilaledu.sch.id',           '252631011', 'XI TO', 'L'],
            ['Hadiqul Aqli',             'hadiqulaqli',           'HadiqulAqli@hilaledu.sch.id',           '252631012', 'XI TO', 'L'],
            ['Hanip Tamami',             'haniptamami',           'HanipTamami@hilaledu.sch.id',           '252631013', 'XI TO', 'L'],
            ['Hari Romadhon',            'hariromadhon',          'HariRomadhon@hilaledu.sch.id',          '252631014', 'XI TO', 'L'],
            ['Ibnu Koyruman',            'ibnukoyruman',          'IbnuKoyruman@hilaledu.sch.id',          '252631015', 'XI TO', 'L'],
            ['Irsyad Nur Mahmudin',      'irsyadnurmahmudin',     'IrsyadNurMahmudin@hilaledu.sch.id',     '252631016', 'XI TO', 'L'],
            ['Jiyad Hidayatullah',       'jiyadhidayatullah',     'JiyadHidayatullah@hilaledu.sch.id',     '252631017', 'XI TO', 'L'],
            ['Mahmud Faaiq Ismail',      'mahmudfaaiqismail',     'MahmudFaaiqIsmail@hilaledu.sch.id',     '252631018', 'XI TO', 'L'],
            ['Maulana Malik Ibrahim',    'maulanamalikibrahim',   'MaulanaMalikIbrahim@hilaledu.sch.id',   '252631019', 'XI TO', 'L'],
            ['Mohammad Silfa',           'mohammadsilfa',         'MohammadSilfa@hilaledu.sch.id',         '252631020', 'XI TO', 'L'],
            ['Muhamad Rafa',             'muhamadrafa',           'MuhamadRafa@hilaledu.sch.id',           '252631021', 'XI TO', 'L'],
            ['Muhammad Amin Ubaidillah', 'muhammadaminubaidillah','MuhammadAminUbaidillah@hilaledu.sch.id','252631022', 'XI TO', 'L'],
            ['Muhammad Dimas',           'muhammaddimas',         'MuhammadDimas@hilaledu.sch.id',         '252631023', 'XI TO', 'L'],
            ['Muhammad Haikal Iman',     'muhammadhaikaliman',    'MuhammadHaikalIman@hilaledu.sch.id',    '252631025', 'XI TO', 'L'],
            ['Muhamad Sekhu Azahidin',   'muhamadsekhuazahidin',  'MuhamadSekhuAzahidin@hilaledu.sch.id',  '252631026', 'XI TO', 'L'],
            ['Nanda Elfiano Pratama',    'nandaelfianopratama',   'NandaElfianoPratama@hilaledu.sch.id',   '252631027', 'XI TO', 'L'],
            ['Nasyatul Fiqry Nadzif',    'nasyatulfiqrynadzif',   'NasyatulFiqryNadzif@hilaledu.sch.id',   '252631028', 'XI TO', 'L'],
            ['Sahlan Ramadhani',         'sahlanramadhani',       'SahlanRamadhani@hilaledu.sch.id',       '252631029', 'XI TO', 'L'],
            ['Syahriel Anugerah',        'syahrielanugerah',      'SyahrielAnugerah@hilaledu.sch.id',      '252631030', 'XI TO', 'L'],
            ['Syahrul Romadhon',         'syahrulromadhon',       'SyahrulRomadhon@hilaledu.sch.id',       '252631031', 'XI TO', 'L'],
            ['Ujang Wawan',              'ujangwawan',            'UjangWawan@hilaledu.sch.id',            '252631032', 'XI TO', 'L'],
            ['Abdul Hakim',              'abdulhakim',            'AbdulHakim@hilaledu.sch.id',            '252631033', 'XI TO', 'L'],
            ['Moh. Amiq Fahmi',          'moh.amiqfahmi',         'Moh.AmiqFahmi@hilaledu.sch.id',         '252631034', 'XI TO', 'L'],
            ['M. Kafa Bihi Al-Haq',      'm.kafabihial-haq',      'M.KafaBihiAl-Haq@hilaledu.sch.id',     '252631035', 'XI TO', 'L'],
            // ── XII TO (16 siswa) ───────────────────────────────────────────
            ['ABDUL HARIS',              'abdulharis',            'ABDULHARIS@hilaledu.sch.id',            '242531001', 'XII TO', 'L'],
            ['ALIF HAFID RIDWAN',        'alifhafidridwan',       'ALIFHAFIDRIDWAN@hilaledu.sch.id',       '242531004', 'XII TO', 'L'],
            ['DWI HANDIKA PRASETIA',     'dwihandikaprasetia',    'DWIHANDIKAPRASETIA@hilaledu.sch.id',    '242531007', 'XII TO', 'L'],
            ['FAHRI',                    'fahri',                 'FAHRI@hilaledu.sch.id',                 '242531008', 'XII TO', 'L'],
            ['ILHAM AKBAR',              'ilhamakbar',            'ILHAMAKBAR@hilaledu.sch.id',            '242531010', 'XII TO', 'L'],
            ['KHOERUL RIZAL',            'khoerulrizal',          'KHOERULRIZAL@hilaledu.sch.id',          '242531011', 'XII TO', 'L'],
            ['MOHAMAD KHAFY JADID ASLHA','mohamadkhafyjadidaslha','MOHAMADKHAFYJADIDASLHA@hilaledu.sch.id','242531014', 'XII TO', 'L'],
            ['MUKHAMMAD REIHAN SAPUTRA', 'mukhammadreihansaputra','MUKHAMMADREIHANSAPUTRA@hilaledu.sch.id','242531015', 'XII TO', 'L'],
            ['MASLANI',                  'maslani',               'MASLANI@hilaledu.sch.id',               '242531017', 'XII TO', 'L'],
            ['NAWAF AFANDI PRATAMA',     'nawafafandipratama',    'NAWAFAFANDIPRATAMA@hilaledu.sch.id',    '242531019', 'XII TO', 'L'],
            ['REZKY PUTRA ADITIYA',      'rezkyputraaditiya',     'REZKYPUTRAADITIYA@hilaledu.sch.id',     '242531022', 'XII TO', 'L'],
            ['RIDHO NUR TAHAR',          'ridhonurtahar',         'RIDHONURTAHAR@hilaledu.sch.id',         '242531023', 'XII TO', 'L'],
            ['SEKHIDUL KAFI',            'sekhidulkafi',          'SEKHIDULKAFI@hilaledu.sch.id',          '242531024', 'XII TO', 'L'],
            ['SUTISNA RAHMAT MAULANA',   'sutisnarahmatmaulana',  'SUTISNARAHMATMAULANA@hilaledu.sch.id',  '242531025', 'XII TO', 'L'],
            ['TIRMAN',                   'tirman',                'TIRMAN@hilaledu.sch.id',                '242531026', 'XII TO', 'L'],
            ['KHAFIYUDIN',               'khafiyudin',            'KHAFIYUDIN@hilaledu.sch.id',            '242531030', 'XII TO', 'L'],
        ];

        $seeded = 0;
        foreach ($data as [$name, $username, $email, $nip, $kelasNama, $gender]) {
            $kelasId = $kelas($kelasNama);
            User::updateOrCreate(
                ['username' => $username],
                [
                    'name'           => $name,
                    'email'          => $email,
                    'password'       => 'siswa123',
                    'password_plain' => 'siswa123',
                    'role'           => 'siswa',
                    'nip'            => $nip,
                    'kelas_id'       => $kelasId,
                    'jenis_kelamin'  => $gender,
                    'jabatan_utama'  => 'Siswa',
                    'is_active'      => true,
                ]
            );
            $seeded++;
        }

        $this->command->info("Siswa seeded ({$seeded} records).");
    }
}
